server:
  port: 8080


spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

  datasource:
    url: jdbc:h2:~/cpass
    username: sa
    password:


api:
  base:
    url: https://nvs-cpaas-oauth.kandy.io/cpaas
